# Generated by Django 4.1.3 on 2023-01-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_carcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='serdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('selcar', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
