# Generated by Django 4.1.3 on 2023-01-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_serdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serdetails',
            old_name='selcar',
            new_name='sertp',
        ),
    ]
