# Generated by Django 4.1.3 on 2023-01-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_selcar_serdetails_sertp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serdetails',
            old_name='company',
            new_name='selcar',
        ),
    ]
