# Generated by Django 4.1.3 on 2023-02-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_company_serdetails_selcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serdetails',
            name='sertp',
        ),
    ]
