# Generated by Django 4.1.3 on 2023-02-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_phone_serdetails_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serdetails',
            old_name='Quantity',
            new_name='phone',
        ),
    ]
