# Generated by Django 4.1.3 on 2023-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_quantity_serdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='serdetails',
            name='manfact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
