# Generated by Django 4.1.3 on 2023-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_serdetails_manfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDCTNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('PRIZE', models.IntegerField(blank=True, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='cart')),
            ],
        ),
    ]
