# Generated by Django 4.1.3 on 2023-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='QUANTITY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serdetails',
            name='QUANTITY',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
