# Generated by Django 4.1.3 on 2023-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_cartdb_quantity_serdetails_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phonenumber', models.IntegerField(blank=True, null=True)),
                ('Emailadress', models.CharField(blank=True, max_length=100, null=True)),
                ('proddb', models.IntegerField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, max_length=500, null=True)),
                ('Date', models.DateField(blank=True, max_length=500, null=True)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
