# Generated by Django 4.1.3 on 2023-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_appointmentdb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdb',
            name='PAYMENT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
