# Generated by Django 4.1.3 on 2023-02-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_paydb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paydb',
        ),
    ]
